# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  request_changes_workflow: true
  path_filters:
    - '!supabase/types.ts'
  pre_merge_checks:
    docstrings:
      mode: 'off'
